package ir.ac.iut.reservation.model;

/**
 * Created by Alireza on 1/20/2017.
 */
public enum Interval {EIGHT_TO_EIGHT_AND_HALf,
    EIGHT_AND_HALf_TO_NINE,
    NINE_TO_NINE_AND_HALf,
    NINE_AND_HALF_TO_TEN,
    TEN_TO_TEN_AND_HALF,
    TEN_AND_HALF_TO_ELEVEN,
    ELEVEN_TO_ELEVEN_AND_HALF,
    ELEVEN_AND_HALF_TO_TWELVE,
    TWELVE_TO_TWELVE_AND_HALF,
    TWELVE_AND_HALF_TO_THIRTEEN,
    THIRTEEN_TO_THIRTEEN_AND_HALF,
    THIRTEEN_AND_HALF_TO_FOURTEEN,
    FOURTEEN_TO_FOURTEEN_AND_HALF,
    FOURTEEN_AND_HALF_TO_FIFTEEN,
    FIFTEEN_TO_FIFTEEN_AND_HALF,
    FIFTEEN_AND_HALF_TO_SIXTEEN,
    SIXTEEN_TO_SIXTEEN_AND_HALF,
    SIXTEEN_AND_HALF_TO_SEVENTEEN,
    SEVENTEEN_TO_SEVENTEEN_AND_HALF,
    SEVENTEEN_AND_HALF_TO_EIGHTEEN,
    EIGHTEEN_TO_EIGHTEEN_AND_HALF,
    EIGHTEEN_AND_HALF_TO_NINETEEN,
    NINETEEN_TO_NINETEEN_AND_HALF,
    NINETEEN_AND_HALF_TO_TWENTY,
    TWENTY_TO_TWENTY_AND_HALF,
    TWENTY_AND_HALF_TO_TWENTYONE
}
